swagger: '2.0'
info:
  title: Test Prod Server
  description: Test Prod Server for testing MCP Server
  version: 1.0.0
host: apps.pubmatic.com
basePath: /
schemes:
  - https
paths:
  /mcpserver/external/mcp:
    post:
      parameters:
        - name: pubToken
          in: header
          type: string
          required: true
          description: Pub Token
          x-ms-visibility: important
        - name: resource-id
          in: header
          type: string
          required: false
          description: Resource id
          x-ms-visibility: important
        - name: resource-type
          in: header
          type: string
          required: false
          description: Resource Type
          x-ms-visibility: important
        - name: Content-Type
          in: header
          type: string
          required: true
          default: application/json
          x-ms-visibility: internal
        - name: Accept
          in: header
          type: string
          required: true
          default: application/json, text/event-stream
          x-ms-visibility: internal
      responses:
        '200':
          description: Immediate Response
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeServer
      summary: Test Prod Server
      description: Test Prod Server for testing MCP Server
securityDefinitions: {}
security: []
